main: com.maboesanman.plugins.Bending.Bending
name: Bending
version: 0.0
author: maboesanman
description: Water, Earth, Fire, Air
commands:
   setelement:
      description: set your bending element.
      usage: /setelement [waterbender, earthbender, firebender, airbender, nonbender] <--choose one
      permission: 
      permission-message: you can't bend that!
